FROM mcr.microsoft.com/dotnet/sdk:5.0 AS build

#WORKDIR /app

COPY ./ApiGateway ./ApiGateway

WORKDIR ./ApiGateway

RUN dotnet publish -c Release -o out

FROM mcr.microsoft.com/dotnet/aspnet:5.0 AS runtime

WORKDIR /app

COPY --from=build ./ApiGateway/out .

CMD dotnet ApiGateway.dll
