version: '3'
services:
  internalDB: 
    image: "mongo:4.2"
    container_name: fc_mongodb_internal
    labels:
      - fc
    env_file:
      - .env
    environment:
      - INTERNAL_MONGO_PORT
    ports:
      - ${INTERNAL_MONGO_PORT}:${DEFAULT_MONGO_PORT} 

  devDB: 
    image: "mongo:4.2"
    container_name: fc_mongodb_neutral
    labels:
      - fc
    ports:
      - ${DEV_MONGO_PORT}:${DEFAULT_MONGO_PORT}

  stagingDB: 
    image: "mongo:4.2"
    container_name: fc_mongodb_staging
    labels:
      - fc
    ports:
      - ${STAGING_MONGO_PORT}:${DEFAULT_MONGO_PORT}

  licensingDB: 
    image: "mongo:4.2"
    container_name: fc_mongodb_licensing
    labels:
      - fc
    env_file:
      - .env
    environment:
      - LICENSING_MONGO_PORT
    ports:
      - ${LICENSING_MONGO_PORT}:${DEFAULT_MONGO_PORT} 

  # update-foodchart:
  #   image: php-update
  #   container_name: update-foodchart
  #   ports:
  #     - "12004:80"
  #     - "12005:443"
  #   volumes:
  #     - .././update-foodchart/:/var/www/html/
  #   links:
  #     - internalDB
  #     - devDB
  #     - stagingDB

  # apiGateway:
  #   image: "fc_gateway"
  #   build: 
  #     context: ../
  #     dockerfile: Docker/dockerfile-apigateway
  #   container_name: fc_gateway
  #   labels:
  #     - fc
  #   links:
  #     - internalDB
  #     - devDB
  #     - stagingDB
  #   ports:
  #     - ${GATEWAY_HTTP_PORT}:${DEFAULT_GATEWAY_HTTP_PORT}
  #     - ${GATEWAY_HTTPS_PORT}:${DEFAULT_GATEWAY_HTTPS_PORT}

  # webClient:
  #   image: "fc_webclient"
  #   build: 
  #     context: ../
  #     dockerfile: Docker/dockerfile-webclient
  #   container_name: fc_webclient
  #   labels:
  #     - fc
  #   ports:
  #     - ${WEB_CLIENT_PORT}:${DEFAULT_PHP_WEB_PORT}
  #     - ${WEB_CLIENT_DEBUG_PORT}:${DEFAULT_PHP_DEBUG_PORT}
  #   volumes:
  #     - ../WebClient/:/var/www/html/
  #   links:
  #     - apiGateway

    # environment: 
    #   MONGO_INITDB_ROOT_USERNAME: root 
    #   MONGO_INITDB_ROOT_PASSWORD: example